{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.13.1.aar",
          "url": "core-ktx-1.13.1.aar",
          "size": 171581,
          "sha512": "26147365d0239ec575eb13bc6741f4f2d05cf7dfe27922df55d0259252e416b07840a87ee58b7a8d72f1480c35cfbab3f6b7178e9cf5f17a984dd07932b8b1a5",
          "sha256": "19ba50d094c7368ede1b4ccf1195ceb83e35970736593f823e5af716f8d05d70",
          "sha1": "f595b8c10fad9099f71a3c1fc6ded1c9b5010190",
          "md5": "fe2ecce12c6e10ec9b3922c5e0d199a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.13.1.aar",
          "url": "core-ktx-1.13.1.aar",
          "size": 171581,
          "sha512": "26147365d0239ec575eb13bc6741f4f2d05cf7dfe27922df55d0259252e416b07840a87ee58b7a8d72f1480c35cfbab3f6b7178e9cf5f17a984dd07932b8b1a5",
          "sha256": "19ba50d094c7368ede1b4ccf1195ceb83e35970736593f823e5af716f8d05d70",
          "sha1": "f595b8c10fad9099f71a3c1fc6ded1c9b5010190",
          "md5": "fe2ecce12c6e10ec9b3922c5e0d199a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.13.1-sources.jar",
          "url": "core-ktx-1.13.1-sources.jar",
          "size": 69704,
          "sha512": "4fe0094a1e18c38c18789f97dac39b7aa6f09852e2ab79620e909dd9135d0a916de8f255e699737f615a67d17d46558a2fc4146a4836aba8aee0fa2d5d4679b2",
          "sha256": "b6646f76cd2d59210561dffb16b32a4e5fcca6de37ca027f1dae82bfb0cf6493",
          "sha1": "2ebeecb97d5b1557fc7b3e3758447b8176e322e8",
          "md5": "a353031ffb18505a1da28589b8b59309"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-ktx-1.13.1-versionMetadata.json",
          "url": "core-ktx-1.13.1-versionMetadata.json",
          "size": 42717,
          "sha512": "d94e7af20884072ba66f3e89dbd1b4e1823156d64bae821674229d47b5a48aa8d552ab42628b5a4d51286814390f8bf4a848006c3653a783e1d324ac6e643eea",
          "sha256": "261dcd3c8616cae91271d5163997c45b8b509af204786420649a0b7e0f245281",
          "sha1": "9ccd1b46b95778109472c0a16ddd08e4bef021f0",
          "md5": "e320a403a93dad70e1c5d328f07a9e93"
        }
      ]
    }
  ]
}