{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.5.2.jar",
          "url": "builder-8.5.2.jar",
          "size": 14158502,
          "sha512": "7035fa3b3e5b1fae33ec6589557275f2e88717a82e201e60c3275965fe2f70b36d04ca4bf6a5dd591c504ec7ce61ff87547dfcaf0f00b46df87c440383df600f",
          "sha256": "1acd72e5fbc20bb20841100b1a98fc1c60c9f1905baa11225022fd1506ed4762",
          "sha1": "e25f77efb95983b9e7f93575e86468a43e6d5784",
          "md5": "34d9f92e7c8be37d6655f5cd30b7aa5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.5.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.5.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.5.2.jar",
          "url": "builder-8.5.2.jar",
          "size": 14158502,
          "sha512": "7035fa3b3e5b1fae33ec6589557275f2e88717a82e201e60c3275965fe2f70b36d04ca4bf6a5dd591c504ec7ce61ff87547dfcaf0f00b46df87c440383df600f",
          "sha256": "1acd72e5fbc20bb20841100b1a98fc1c60c9f1905baa11225022fd1506ed4762",
          "sha1": "e25f77efb95983b9e7f93575e86468a43e6d5784",
          "md5": "34d9f92e7c8be37d6655f5cd30b7aa5e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.5.2-javadoc.jar",
          "url": "builder-8.5.2-javadoc.jar",
          "size": 397693,
          "sha512": "6e65eddcacc9788e14aa471ab8c5675be781a8726985d1bb720a94182fa8d395a9b092b2287dfe14d03a939f9fe1bc93f278c2032dd60e4f0ce2e3199f9bab1b",
          "sha256": "4efbb17c99beb355867fc147c26ac94c10ad9b0f27d9608f7ec7f100a53aa04e",
          "sha1": "54dd09860c78b1a6db84707e92c6b9632de945bf",
          "md5": "a5c420f9dc762e1dab88b0a0c909de78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.5.2-sources.jar",
          "url": "builder-8.5.2-sources.jar",
          "size": 280881,
          "sha512": "a14c11bcc15cf395e6ea7217f84410420486f926ea38e79e9b0dce4ef7bec928c7a19a61fe5b290afb32df444a0a16860d8cff78d410db89a7676af949250214",
          "sha256": "4461b37bc2ab3f0234f4cc9de6be2e1c88c2f1ca60b221a9c1254013a0b44a73",
          "sha1": "2aafc2e4d7d1c86e37c18d7ed65506558b6fc975",
          "md5": "a879f70dc911ff5c8ec709fd25aee692"
        }
      ]
    }
  ]
}
